<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-2AD7C06" ignored="1" name="Personal loan" tests="5" failures="1" timestamp="09 Sep 2020 05:13:30 GMT" time="0.079" errors="0">
  <testcase name="demo" time="0.011" classname="test.demo1">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at test.demo1.demo(demo1.java:21)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- demo -->
  <testcase name="ploan" time="0.009" classname="test.demo2"/>
  <testcase name="LoginAPIHomeLoan" time="0.002" classname="test.demo4"/>
  <testcase name="MobileloginHomeLoan" time="0.011" classname="test.demo4"/>
  <testcase name="WebloginHomeLoan" time="0.002" classname="test.demo4"/>
  <testcase name="SecondTest" time="0.0" classname="test.demo1">
    <ignored/>
  </testcase> <!-- SecondTest -->
</testsuite> <!-- Personal loan -->
